'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const features=window.ESTATE.features, byId=new Map(features.map(f=>[f.id,f]));
// Edition 15: garden detail traced from 2026 aerial imagery replaces the source footways and boundaries inside the walled and fenced gardens.
const GD=window.GARDENS||{features:[],superseded_ways:[],superseded_barriers:[],routing_segments:[],connectors:[]};
const supersededWays=new Set(GD.superseded_ways),supersededBarriers=new Set(GD.superseded_barriers);
const map=L.map('map',{crs:window.estateCRS,preferCanvas:true,zoomControl:false,minZoom:14,maxZoom:21,zoomSnap:.25,attributionControl:true}).setView([38.7106,-77.0867],16);
L.control.zoom({position:'bottomright'}).addTo(map);L.control.scale({imperial:false,position:'bottomleft',maxWidth:100}).addTo(map);
map.attributionControl.addAttribution('© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>');
for(const [n,z] of [['water',210],['land',220],['boundary',225],['parking',240],['barriers',315],['paths',300],['gardenWalks',306],['gardenBarriers',318],['hits',345],['buildings',350],['route',440],['location',460]]){map.createPane(n);map.getPane(n).style.zIndex=z;}
window.addEstateBake(map);
const groups={water:L.layerGroup(),land:L.layerGroup(),parking:L.layerGroup(),barriers:L.layerGroup(),paths:L.layerGroup(),buildings:L.layerGroup(),places:L.layerGroup().addTo(map),signs:L.layerGroup()},routeLayer=L.layerGroup().addTo(map),aiRouteLayer=L.layerGroup().addTo(map);
// Keep the first paint light. Reference geometry is prepared only when a user
// asks for that layer, while the baked watercolor atlas remains immediately visible.
const pendingLayers={water:[],land:[],parking:[],barriers:[],paths:[],buildings:[],signs:[]};
const loadedLayers=new Set();
const pathTypes=new Set(['footway','path','pedestrian','steps','cycleway','bridleway','track','service','residential','living_street','unclassified']);
const isArea=f=>['Polygon','MultiPolygon'].includes(f.geometry.type), isLine=f=>['LineString','MultiLineString'].includes(f.geometry.type);
const featureCenters=new Map();
function center(f){if(featureCenters.has(f.id))return featureCenters.get(f.id);let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity;function visit(c){if(typeof c[0]==='number'){x0=Math.min(x0,c[0]);x1=Math.max(x1,c[0]);y0=Math.min(y0,c[1]);y1=Math.max(y1,c[1]);}else c.forEach(visit);}visit(f.geometry.coordinates);const result=[(y0+y1)/2,(x0+x1)/2];featureCenters.set(f.id,result);return result;}
const hitRenderer=L.canvas({pane:'hits',padding:.3,tolerance:matchMedia('(pointer:coarse)').matches?14:5});
const renderers=Object.fromEntries(['water','land','parking','barriers','paths','buildings'].map(p=>[p,window.createEstateRenderer(p)]));
function layer(f,group,style){const g=L.geoJSON(f,{pane:group,renderer:renderers[group],interactive:group==='buildings',smoothFactor:.7,style,pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:4})});if(group==='buildings')g.on('click',e=>{const p=placeById.get(f.id);if(p)tapPlace(p,e.latlng);else showFeature(f);});if(group==='parking'){const p=f.properties||{},cap=p.capacity?' · '+esc(p.capacity)+' spaces':'';g.bindTooltip(esc(p.name||'Parking')+cap,{className:'access-tooltip',direction:'top',sticky:true});}if(group==='barriers'){const p=f.properties||{},kind=p.barrier==='wall'||p.fence_type==='brick'?'wall':p.barrier||'boundary';g.bindTooltip(kind==='wall'?'Historic wall / masonry boundary':kind==='hedge'?'Hedge boundary':'Fence / garden boundary',{className:'access-tooltip',direction:'top',sticky:true});g.bindPopup('<strong>'+esc(kind==='wall'?'Historic wall / masonry boundary':kind==='hedge'?'Hedge boundary':'Fence / garden boundary')+'</strong><br>Source-derived boundary. Current access and gate status require estate confirmation.<br><a target="_blank" rel="noreferrer" href="https://www.openstreetmap.org/'+f.id+'">Open source record</a>');}g.addTo(groups[group]);return g;}
function registerLayer(f,group,style){pendingLayers[group].push([f,style]);}
function ensureLayer(name){if(loadedLayers.has(name)||!pendingLayers[name])return;for(const [f,style] of pendingLayers[name])layer(f,name,style);loadedLayers.add(name);}
function barrierStyle(p){const wall=p.barrier==='wall'||p.fence_type==='brick';const hedge=p.barrier==='hedge';return {color:wall?'#9b8873':hedge?'#829071':'#a09d80',weight:wall?2:hedge?2:1.4,opacity:wall?.43:hedge?.34:.28,dashArray:wall?null:hedge?'1 6':'4 5',lineCap:'round',lineJoin:'round'};}
// Edition 25 includes roads and walks in the artwork. The optional reference
// layer separates them: carriage drives and service roads read heavy and dark,
// visitor walks light and fine, steps and cycleways get their own marks.
const walkTypes=new Set(['footway','path','pedestrian','corridor']);
const roadTypes=new Set(['motorway','trunk','primary','secondary','tertiary','unclassified','residential','living_street','road','motorway_link','trunk_link','primary_link','secondary_link','tertiary_link']);
function pathStyle(p){const h=p.highway;
 if(h==='steps')return {color:'#a8571f',weight:2.6,dashArray:'2 3',lineCap:'butt',opacity:.95};
 if(h==='cycleway')return {color:'#4e7f97',weight:2,dashArray:'7 4',lineCap:'round',opacity:.9};
 if(walkTypes.has(h))return {color:['asphalt','concrete','paving_stones','paved'].includes(p.surface)?'#b8bdb2':'#d6c6a2',weight:1.8,lineCap:'round',lineJoin:'round',opacity:.95};
 if(h==='track'||h==='bridleway')return {color:'#9d7f4e',weight:1.8,dashArray:'6 4',lineCap:'round',opacity:.85};
 if(h==='service')return {color:'#8a7a60',weight:3,lineCap:'round',lineJoin:'round',opacity:.8};
 if(roadTypes.has(h))return {color:'#626c6b',weight:4.5,lineCap:'round',lineJoin:'round',opacity:.8};
 return {color:'#9b7550',weight:2,lineCap:'round',lineJoin:'round',opacity:.85};}
// Optional parking outlines provide source geometry for inspection, separate
// from the parking markings already visible in the artwork.

const parkingStyle={color:'#7d7058',weight:1.6,dashArray:'5 3',fill:true,fillColor:'#d3c8ab',fillOpacity:.32,opacity:.9,lineJoin:'round'};
const estate=byId.get('way/232724526');
// Optional reference geometry. The default map is a baked 3D illustration.
features.forEach(f=>{const p=f.properties;
 if(isArea(f)&&(p.landuse||p.leisure||p.natural)&&!p.building){registerLayer(f,'land',{color:'#597250',weight:1,fill:false,opacity:.65});}
 if(p.barrier&&isLine(f)&&!supersededBarriers.has(f.id)){registerLayer(f,'barriers',barrierStyle(p));}
 if(isArea(f)&&(p.amenity==='parking'||p.amenity==='parking_space')){registerLayer(f,'parking',parkingStyle);}
 if(p.highway&&isLine(f)&&!supersededWays.has(f.id)){const copy={...f,geometry:{...f.geometry,coordinates:f.geometry.type==='LineString'?window.estateDensify(f.geometry.coordinates):f.geometry.coordinates.map(window.estateDensify)}};registerLayer(copy,'paths',pathStyle(p));}
 if(p.building&&isArea(f)){registerLayer(f,'buildings',{color:'#713e29',weight:1.3,lineCap:'round',lineJoin:'round',fill:false,opacity:.9});}
 if(p.tourism==='information'||p.information||p.traffic_sign){L.circleMarker(center(f),{radius:6,color:'#fff',weight:2,fillColor:'#426e94',fillOpacity:1}).bindPopup('<strong>'+esc(p.name||'Mapped information')+'</strong><br>'+esc(p.information||p.tourism||'Sign')+'<br><a target="_blank" rel="noreferrer" href="https://www.openstreetmap.org/'+f.id+'">Open source record</a>').addTo(groups.signs);}
});

// Layers ticked in the markup never fire a change event, so anything on by
// default has to be built and added here as well.


// Garden detail layer (Edition 15): walks, walls, fences and hedges traced from 2026 aerial imagery.
// Widths are expressed in metres and rescaled on every zoom change so the drawing stays in step with the baked ground.
const gardenRenderer=L.canvas({pane:'gardenBarriers',padding:.2,tolerance:4});
const gardenWalkRenderer=L.canvas({pane:'gardenWalks',padding:.2,tolerance:4});
groups.gardens=L.layerGroup();
const gardenScaled=[];// [layer, {weight_m, minPx, dash_m:[on,off]|null}]
const proj=ll=>map.options.crs.projection.project(L.latLng(ll[1],ll[0]));
const unproj=p=>{const ll=map.options.crs.projection.unproject(p);return [ll.lat,ll.lng];};
function wormLine(coords,panel=3.3,amp=1.0){// zigzag rails: alternate sides of the traced fence line
 const pts=coords.map(proj),out=[];let side=1;
 for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],len=a.distanceTo(b),n=Math.max(1,Math.round(len/panel)),dx=(b.x-a.x)/len,dy=(b.y-a.y)/len;
  for(let j=0;j<n;j++){const t=(j+.5)/n,mx=a.x+(b.x-a.x)*t,my=a.y+(b.y-a.y)*t;if(!out.length)out.push(unproj(a));out.push(unproj(L.point(mx-dy*amp*side,my+dx*amp*side)));side=-side;}
  out.push(unproj(b));}
 return out;}
function gardenLine(latlngs,pane,style,scale){const l=L.polyline(latlngs,{pane,renderer:pane==='gardenWalks'?gardenWalkRenderer:gardenRenderer,interactive:!!style.interactive,lineCap:style.lineCap||'round',lineJoin:'round',...style});gardenScaled.push([l,scale]);l.addTo(groups.gardens);return l;}
const gardenTip=(l,text)=>l.bindTooltip(text,{className:'access-tooltip',direction:'top',sticky:true});
const gardenLines=GD.features.filter(f=>f.geometry.type==='LineString');
const toLL=g=>g.coordinates.map(c=>[c[1],c[0]]);
// walks: all casings first, then all fills, so junctions read as one continuous surface
for(const f of gardenLines){const p=f.properties;if(p.kind!=='walk'||p.casing===false)continue;gardenLine(toLL(f.geometry),'gardenWalks',{color:p.surface==='grass'?'#abc871':'#baa66b',opacity:.9,lineCap:'butt'},{w:p.width_m+0.5,min:1.5});}
for(const f of gardenLines){const p=f.properties;if(p.kind!=='walk')continue;const grass=p.surface==='grass';
 const fill=gardenLine(toLL(f.geometry),'gardenWalks',{color:grass?'#c6e18b':'#e9e2ab',opacity:1,lineCap:'butt',interactive:true},{w:p.width_m,min:1});
 gardenTip(fill,esc(p.name)+' · '+(grass?'grass walk':'gravel walk')+' · about '+p.width_m+' m wide');}
for(const f of gardenLines){const p=f.properties,g=f.geometry,ll=toLL(g);
 if(p.kind==='wall'){gardenLine(ll,'gardenBarriers',{color:'#54351b',opacity:.5},{w:1.0,min:3});const w=gardenLine(ll,'gardenBarriers',{color:'#a97b5b',opacity:1,interactive:true},{w:.6,min:2});gardenTip(w,esc(p.name)+' · brick wall');}
 else if(p.kind==='fence'){
  if(p.fence_type==='worm'){const z=wormLine(g.coordinates);const w=gardenLine(z,'gardenBarriers',{color:'#40270d',opacity:.9,lineJoin:'miter',interactive:true},{w:.22,min:1.2});gardenTip(w,esc(p.name)+' · split-rail worm fence');}
  else{gardenLine(ll,'gardenBarriers',{color:'#503617',opacity:.8,lineCap:'butt'},{w:.15,min:1});const posts=gardenLine(ll,'gardenBarriers',{color:'#3c2308',opacity:.95,lineCap:'butt',interactive:true},{w:.45,min:1.6,dash:[.4,2.9]});gardenTip(posts,esc(p.name)+' · post-and-rail fence');}}
 else if(p.kind==='hedge'){const h=gardenLine(ll,'gardenBarriers',{color:'#4e7a35',opacity:.75,lineCap:'round',interactive:true},{w:.5,min:1.5,dash:[1.0,.7]});gardenTip(h,esc(p.name)+' · box hedge');}
}
function rescaleGardens(){const s=Math.pow(2,map.getZoom()-17);for(const[l,sc]of gardenScaled){const w=Math.max(sc.min,sc.w*s);const o={weight:w};o.dashArray=sc.dash?sc.dash.map(m=>Math.max(1,m*s)).join(' '):null;l.setStyle(o);}}
map.on('zoomend',rescaleGardens);rescaleGardens();

// Edition 25 depicts the curated site edge in the artwork.
L.marker([38.7078,-77.0800],{interactive:false,icon:L.divIcon({className:'',html:'<div class="river-label">Potomac River</div>',iconSize:[220,30]})}).addTo(map);
let gpsMarker=null,gpsAccuracy=null,currentLocation=null;
function setLocation(ll,accuracy){currentLocation={lat:ll.lat,lng:ll.lng,accuracy_m:Math.round(accuracy||0),timestamp:new Date().toISOString()};if(gpsMarker)map.removeLayer(gpsMarker);if(gpsAccuracy)map.removeLayer(gpsAccuracy);gpsAccuracy=L.circle(ll,{pane:'location',radius:Math.max(accuracy||0,8),color:'#126e70',weight:1,fillColor:'#126e70',fillOpacity:.10}).addTo(map);gpsMarker=L.circleMarker(ll,{pane:'location',radius:7,color:'#fff',weight:3,fillColor:'#126e70',fillOpacity:1}).bindTooltip('Your location',{direction:'top',className:'access-tooltip'}).addTo(map);$('locationStatus').hidden=false;$('locationStatus').classList.remove('is-error');$('locationStatus').textContent='Location found · accuracy about '+Math.max(1,Math.round(accuracy||0))+' m. Routes remain on mapped paths.';}
function locationError(err){$('locationStatus').hidden=false;$('locationStatus').classList.add('is-error');$('locationStatus').textContent=err&&err.code===1?'Location permission was not granted.':'Location is unavailable here. You can still plan from a selected place.';}
$('locate').onclick=()=>{if(!navigator.geolocation){locationError({code:2});return;}$('locationStatus').hidden=false;$('locationStatus').classList.remove('is-error');$('locationStatus').textContent='Finding your location…';navigator.geolocation.getCurrentPosition(pos=>{const ll=L.latLng(pos.coords.latitude,pos.coords.longitude);setLocation(ll,pos.coords.accuracy);map.setView(ll,Math.max(map.getZoom(),17.5),{animate:true});},locationError,{enableHighAccuracy:true,maximumAge:30000,timeout:12000});};
const curated=[['way/189853023','The Mansion','Historic house'],['way/232717210','Upper Garden','Gardens & grounds'],['way/232717207','Lower Garden','Gardens & grounds'],['way/43932369','Bowling Green','Gardens & grounds'],['way/334219851',"Washington’s Tomb",'Memorials & remembrance'],['node/2410476835','Slave Memorial','Source name · memorial'],['way/232718150','Old Tomb','Historic structure'],['way/232718134','The Farm','Agriculture & working life'],['way/232605898','16-Sided Barn','Agriculture & working life'],['way/232605874','Wharf','Along the river'],['way/189853024','Greenhouse & quarters','Historic working spaces'],['way/232715247','Ford Orientation Center','Arrival'],['way/122023877','Museum & Education Center','Museum'],['way/232605866','Blacksmith Shop','Historic working spaces'],['way/232605900','Kitchen','Historic working spaces'],['way/232718129','Fruit Garden & Nursery','Gardens & grounds']];
const coreBox=[-77.0912,38.7040,-77.0838,38.7107];
const categorize=n=>{const t=n.toLowerCase();if(/tomb|memorial/.test(t))return 'Memorials & remembrance';if(/museum|education|orientation|library|administration|gate|entrance|interpretive|restroom/.test(t))return 'Visitor facilities';if(/barn|sheep|hog|oxen|paddock|chicken|shelter|batteau|farm/.test(t))return 'Agriculture & working life';if(/garden|necessary|bowling/.test(t))return 'Gardens & grounds';if(/wharf/.test(t))return 'Along the river';if(/mansion/.test(t))return 'Historic house';return 'Historic working spaces';};
const curatedIds=new Set(curated.map(x=>x[0]));
const extras=features.filter(f=>f.properties.building&&f.properties.name&&isArea(f)&&!curatedIds.has(f.id)).map(f=>{const c=center(f);return {f,c};}).filter(({c})=>c[0]>=coreBox[1]&&c[0]<=coreBox[3]&&c[1]>=coreBox[0]&&c[1]<=coreBox[2]).map(({f})=>[f.id,f.properties.name,categorize(f.properties.name)]).sort((a,b)=>a[2].localeCompare(b[2])||a[1].localeCompare(b[1]));
const places=[...curated.filter(x=>byId.has(x[0])),...extras].map((x,i)=>({id:x[0],name:x[1],category:x[2],feature:byId.get(x[0]),index:i+1,curated:curatedIds.has(x[0])}));const placeById=new Map(places.map(p=>[p.id,p]));
const accessProfiles={
 'way/232717207':{label:'Walled kitchen garden',boundary:'Brick wall on every side; openings beside the Garden House (west), at the north-east corner and at the south-east corner',routing:'Enter through one of the three wall openings, then keep to the gravel perimeter walks, the cross walks or the central grass walk. Planting compartments and box hedges are not walkable.',source:'Walls, walks and compartments traced from 2026 aerial imagery; gate positions need estate confirmation.'},
 'way/232717210':{label:'Walled formal garden',boundary:'Brick wall from the Garden House to the greenhouse and along the Bowling Green side; the greenhouse closes the north-east side',routing:'Enter beside the Garden House or from the greenhouse forecourt. Use the perimeter walks, the wide cross walk and the three north-south walks; the parterres and vegetable compartments are box-edged beds.',source:'Walls, walks and compartments traced from 2026 aerial imagery; gate positions need estate confirmation.'},
 'way/232718129':{label:'Fenced fruit garden and nursery',boundary:'Post-and-rail fence around the whole enclosure, with a second fence dividing the vegetable plots from the orchard',routing:'Enter where the gravel cross walk passes through the west or east fence, or from the north walk. Only the cross walk and the north walk are paths; the orchard quarters and plots are cultivated ground.',source:'Fences, walks and plots traced from 2026 aerial imagery; gate positions need estate confirmation.'},
 'way/232718134':{label:'Worm-fenced crop fields',boundary:'Split-rail worm fences line both sides of the field lane and the outer edges of the fields',routing:'Stay on the north lane, the field lane or the river path. The fields between the fences are crops, not lawn.',source:'Fence and field layout interpreted from 2026 aerial imagery and placed against the mapped lanes; not surveyed.'},
 'way/43932369':{label:'Open lawn / visitor grounds',boundary:'Landscape edge varies',routing:'Stay on mapped paths where available; lawn access may be seasonal or event-dependent.'}
};
const accessMode={profile:'visitor',stepFree:false};
let chosen=null,stops=[],routeSegments=[],gaps=[],routeMeters=0;
const touch=matchMedia('(pointer:coarse)').matches;
const markers=[];places.forEach(p=>{p.ll=L.latLng(center(p.feature));const size=p.curated?(touch?32:25):(touch?24:18);const m=L.marker(p.ll,{icon:L.divIcon({className:'poi-marker',html:'<span class="poi-dot'+(p.curated?'':' minor')+'">'+p.index+'</span>',iconSize:[size,size],iconAnchor:[size/2,size/2]}),keyboard:true,title:p.name}).on('click',e=>tapPlace(p,e.latlng)).addTo(groups.places);m.bindTooltip(p.name,{permanent:false,direction:'right',className:'map-label',offset:[0,0]});markers.push([p,m]);});
// Every place footprint is tappable at all zooms, without needing the reference building layer.
const hitLayer=L.layerGroup().addTo(map);
for(const p of places){if(!isArea(p.feature))continue;L.geoJSON(p.feature,{pane:'hits',renderer:hitRenderer,style:{color:'#1c6260',weight:touch?10:4,opacity:0,fillOpacity:0},interactive:true}).on('click',e=>{L.DomEvent.stop(e);tapPlace(p,e.latlng);}).addTo(hitLayer);}
let tapPopup=null;
function tapPlace(p,ll){// quick popup: name, category, Details, Add to route. No camera move, so the visitor keeps their bearings.
 if(tapPopup)map.closePopup(tapPopup);
 const inRoute=stops.some(s=>s.id===p.id);
 tapPopup=L.popup({className:'tap-popup',closeButton:true,autoPan:true,autoPanPadding:[20,80],offset:[0,-6],maxWidth:260}).setLatLng(ll||p.ll).setContent('<span class="eyebrow">'+esc(p.category)+'</span><strong>'+esc(p.name)+'</strong><div class="tap-actions"><button data-details="'+p.id+'">Details</button><button data-add="'+p.id+'" class="primary">'+(inRoute?'In your route ✓':'Add to route +')+'</button></div>').openOn(map);
 const el=tapPopup.getElement();el.querySelector('[data-details]').onclick=()=>{map.closePopup(tapPopup);select(p,{fly:false});};el.querySelector('[data-add]').onclick=()=>{if(!inRoute){stops.push({...p,ll:L.latLng(center(p.feature))});renderRoute();}map.closePopup(tapPopup);setTab('tour');};
 for(const[pp,m]of markers)m.getElement()?.querySelector('.poi-dot')?.classList.toggle('selected',pp.id===p.id);
}
function updateLabels(){const z=map.getZoom();for(const[p,m]of markers){const permanent=p.curated?(z>=18||(z>=16.75&&[1,2,3,5,6,8,10,12].includes(p.index))||(z>=15.5&&[1,5,8].includes(p.index))):z>=18.75;const t=m.getTooltip();if(t.options.permanent!==permanent){m.unbindTooltip();m.bindTooltip(p.name,{permanent,direction:p.index%2?'right':'left',className:'map-label',offset:[0,0]});}}}
map.on('zoomend',updateLabels);
function updateMinor(){const show=map.getZoom()>=18;for(const[p,m]of markers){if(!p.curated){const el=m.getElement();if(el)el.style.display=show?'':'none';}}}
map.on('zoomend',updateMinor);map.whenReady(updateMinor);
function renderPlaces(query=''){const q=query.toLowerCase();let result=places.filter(p=>(p.name+' '+p.category+' '+(p.feature.properties.name||'')).toLowerCase().includes(q));if(q){for(const f of features){if(f.properties.name&&!placeById.has(f.id)&&f.properties.name.toLowerCase().includes(q)&&(f.properties.building||f.properties.historic||f.properties.tourism)){result.push({id:f.id,name:f.properties.name,category:f.properties.building?'Building':'Mapped place',feature:f,index:'·'});}}}result=result.slice(0,80);const btn=p=>'<button class="place'+(p.curated?'':' minor')+'" data-id="'+p.id+'"><span class="num">'+p.index+'</span><span><strong>'+esc(p.name)+'</strong><small>'+esc(p.category)+'</small></span><span class="arrow">›</span></button>';
 let html='';if(!q){html+='<h3 class="group">Highlights</h3>'+result.filter(p=>p.curated).map(btn).join('');const rest=result.filter(p=>!p.curated);let cat=null;for(const p of rest){if(p.category!==cat){cat=p.category;html+='<h3 class="group">'+esc(cat)+'</h3>';}html+=btn(p);}}else html=result.map(btn).join('');
 $('placeList').innerHTML=result.length?html:'<p class="fine">No mapped places match your search.</p>';document.querySelectorAll('.place').forEach(b=>b.onclick=()=>{const p=result.find(p=>p.id===b.dataset.id);select(p);});}
function showFeature(f){select(placeById.get(f.id)||{id:f.id,name:f.properties.name||'Mapped building',category:'Building',feature:f,index:'·'});}
function select(p,opts={fly:true}){chosen={...p,ll:L.latLng(center(p.feature))};if(opts.fly!==false)map.setView(chosen.ll,Math.max(map.getZoom(),17.5),{animate:true});$('detail').hidden=false;const prop=p.feature.properties,art=window.ESTATE_LANDMARKS[p.id]||(p.id==='way/232717210'?{asset:'upperGarden'}:p.id==='way/232717207'?{asset:'lowerGarden'}:null),access=accessProfiles[p.id],accessHtml=access?'<div class="access-card"><strong>'+esc(access.label)+'</strong><span>'+esc(access.boundary)+'</span><p>'+esc(access.routing)+'</p><small>Access note: '+esc(access.source||'Source-derived map interpretation.')+'</small></div>':'';$('detail').innerHTML=(art?'<img class="detail-watercolor" src="'+window.ESTATE_ART_URLS[art.asset]+'" alt="Watercolor illustration of '+esc(p.name)+'">':'')+'<button class="close" id="closeDetail" aria-label="Close place details">×</button><span class="eyebrow">'+esc(p.category)+'</span><h2>'+esc(p.name)+'</h2><p>'+esc(prop.name&&prop.name!==p.name?'Source: '+prop.name:prop.building?(p.curated?'Mapped building footprint':'Historic outbuilding · mapped footprint, audio slot open'):'Mapped estate place')+'</p>'+accessHtml+'<button id="addStop" class="primary">'+(stops.some(s=>s.id===p.id)?'Already in your route':'Add to your route +')+'</button><p class="fine">Audio not attached · <a target="_blank" rel="noreferrer" href="https://www.openstreetmap.org/'+p.id+'">Source record ↗</a></p>';$('closeDetail').onclick=()=>$('detail').hidden=true;$('addStop').onclick=()=>{if(!stops.some(s=>s.id===chosen.id)){stops.push({...chosen});renderRoute();}setTab('tour');$('detail').hidden=true;};}
function setTab(t){$('places').hidden=t!=='places';$('tour').hidden=t!=='tour';for(const[id,yes]of [['exploreTab',t==='places'],['tourTab',t==='tour']]){$(id).classList.toggle('active',yes);$(id).setAttribute('aria-selected',yes);}}
$('exploreTab').onclick=()=>setTab('places');$('tourTab').onclick=()=>setTab('tour');$('search').oninput=e=>renderPlaces(e.target.value);
$('layersButton').onclick=()=>{$('layers').hidden=!$('layers').hidden;$('layersButton').setAttribute('aria-expanded',!$('layers').hidden);};
document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=()=>{const name=c.dataset.layer;if(c.checked){ensureLayer(name);groups[name].addTo(map);}else map.removeLayer(groups[name]);});
$('home').onclick=()=>map.fitBounds([[38.7035,-77.0987],[38.7169,-77.0777]],{padding:[35,35]});$('core').onclick=()=>map.fitBounds([[38.7064,-77.0900],[38.7101,-77.0848]],{padding:[28,28]});
// Walking graph: exact shared coordinate keys, no invented bridges between disconnected ways.
const graph=new Map(),nodeLL=new Map();const key=c=>c[0].toFixed(7)+','+c[1].toFixed(7);function connect(a,b){const ka=key(a),kb=key(b);for(const[k,c]of [[ka,a],[kb,b]]){if(!graph.has(k))graph.set(k,[]);nodeLL.set(k,L.latLng(c[1],c[0]));}const distance=nodeLL.get(ka).distanceTo(nodeLL.get(kb));graph.get(ka).push([kb,distance]);graph.get(kb).push([ka,distance]);}
features.forEach(f=>{const p=f.properties;if(supersededWays.has(f.id)||!pathTypes.has(p.highway)||!isLine(f)||['no','private'].includes(p.access)||['no','private'].includes(p.foot)||p.construction)return;const lines=f.geometry.type==='LineString'?[f.geometry.coordinates]:f.geometry.coordinates;for(const line of lines)for(let i=1;i<line.length;i++)connect(line[i-1],line[i]);});
GD.routing_segments.forEach(([a,b])=>connect(a,b));GD.connectors.forEach(([a,b])=>connect(a,b));
function nearest(ll){let best=null,d=Infinity;for(const[k,p]of nodeLL){const x=ll.distanceTo(p);if(x<d){best=k;d=x;}}return {key:best,distance:d};}
function shortest(start,end){if(!start||!end)return null;const dist=new Map([[start,0]]),prev=new Map(),queue=[[0,start]],seen=new Set();while(queue.length){queue.sort((a,b)=>b[0]-a[0]);const[d,k]=queue.pop();if(seen.has(k))continue;seen.add(k);if(k===end){let path=[k];while(prev.has(path[0]))path.unshift(prev.get(path[0]));return {coords:path.map(n=>[nodeLL.get(n).lng,nodeLL.get(n).lat]),meters:d};}for(const[n,w]of graph.get(k)||[]){const nd=d+w;if(nd<(dist.get(n)??Infinity)){dist.set(n,nd);prev.set(n,k);queue.push([nd,n]);}}}return null;}
function renderRoute(){routeLayer.clearLayers();routeSegments=[];gaps=[];routeMeters=0;for(let i=0;i<stops.length;i++){const s=stops[i];s.snap=nearest(s.ll);L.marker(s.ll,{icon:L.divIcon({className:'route-pin',html:String(i+1),iconSize:[27,27],iconAnchor:[13,13]})}).addTo(routeLayer);if(s.snap.distance>60)gaps.push('Stop '+(i+1)+' is '+Math.round(s.snap.distance)+' m from a mapped path.');if(accessProfiles[s.id])gaps.push(accessProfiles[s.id].label+' is path-only; do not cross planting beds or boundaries.');if(i){const seg=shortest(stops[i-1].snap.key,s.snap.key);if(seg){routeSegments.push({...seg,from:stops[i-1].id,to:s.id});routeMeters+=seg.meters;const ll=window.estateDensify(seg.coords).map(c=>[c[1],c[0]]);L.polyline(ll,{pane:'route',color:'#fff9e9',weight:8,opacity:.95}).addTo(routeLayer);L.polyline(ll,{pane:'route',color:'#126e70',weight:4,dashArray:'9 5',lineCap:'round'}).addTo(routeLayer);}else gaps.push('No connected mapped path between stops '+i+' and '+(i+1)+'.');}}
$('routeCount').textContent=stops.length;$('stops').innerHTML=stops.map((s,i)=>'<li><span>'+esc(s.name)+'</span><button data-up="'+i+'" aria-label="Move '+esc(s.name)+' earlier" '+(i===0?'disabled':'')+'>↑</button><button data-remove="'+i+'" aria-label="Remove '+esc(s.name)+'">×</button></li>').join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{stops.splice(Number(b.dataset.remove),1);renderRoute();});document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.up);if(i>0)[stops[i-1],stops[i]]=[stops[i],stops[i-1]];renderRoute();});const maxSnap=stops.length?Math.max(...stops.map(s=>s.snap.distance)):0;$('routeStatus').textContent=stops.length<2?(stops.length?((gaps.length?gaps.join(' ')+' ':'')+'Add another place to draw your path.'):'Your first stop begins the journey.'):(Math.round(routeMeters)+' m of mapped path · '+stops.length+' stops. '+(gaps.length?gaps.join(' '):'Route connected. ')+'Stop-to-path offsets up to '+Math.round(maxSnap)+' m; final approaches are not routed.');$('export').disabled=!stops.length;}
$('clear').onclick=()=>{stops=[];renderRoute();};
function exportRoute(){return {type:'FeatureCollection',name:'Mount Vernon tour',metadata:{source:'OpenStreetMap contributors',license:'ODbL-1.0',snapshot:'2026-09-11',status:'Unvalidated planning preview',access_profile:accessMode.profile,step_free_requested:accessMode.stepFree,distance_m:Math.round(routeMeters),warnings:gaps,barriers_visible:true,final_approaches_routed:false,current_location:currentLocation},features:[...stops.map((s,i)=>({type:'Feature',id:s.id,properties:{name:s.name,order:i+1,osm_id:s.id,audio_url:null,snap_distance_m:Math.round(s.snap.distance),access_note:accessProfiles[s.id]?.routing||null,path_coordinate:s.snap.key?[nodeLL.get(s.snap.key).lng,nodeLL.get(s.snap.key).lat]:null},geometry:{type:'Point',coordinates:[s.ll.lng,s.ll.lat]}})),...routeSegments.map((s,i)=>({type:'Feature',properties:{kind:'route',segment:i+1,from:s.from,to:s.to,length_m:Math.round(s.meters)},geometry:{type:'LineString',coordinates:s.coords}}))]};}
$('export').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(exportRoute(),null,2)],{type:'application/geo+json'}));a.href=url;a.download='mount-vernon-tour.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function setAccessProfile(profile){accessMode.profile=profile==='accessible'?'accessible':'visitor';accessMode.stepFree=accessMode.profile==='accessible';return {...accessMode};}
function applyAiRoute(fc){aiRouteLayer.clearLayers();if(!fc||fc.type!=='FeatureCollection'||!Array.isArray(fc.features))return {accepted:false,warnings:['Expected a GeoJSON FeatureCollection with a features array.']};const lines=fc.features.filter(f=>f&&f.geometry&&['LineString','MultiLineString'].includes(f.geometry.type));if(!lines.length)return {accepted:false,warnings:['No route line was supplied.']};const warnings=[];const layer=L.geoJSON({type:'FeatureCollection',features:lines},{pane:'route',style:{color:'#80563d',weight:9,opacity:.92,lineCap:'round',lineJoin:'round'},onEachFeature:(f,l)=>l.bindTooltip(f.properties?.instruction||'AI-planned route',{className:'access-tooltip',sticky:true})}).addTo(aiRouteLayer);if(fc.metadata?.warnings?.length)warnings.push(...fc.metadata.warnings);return {accepted:true,segments:lines.length,warnings,layer};}
function getNavigationContext(){return {schema:'mount-vernon-navigation-context/v1',source:{osm_snapshot:'2026-09-11',landscape_reference:'Fairfax County / EagleView 2025',status:'planning preview'},access:{profile:accessMode.profile,step_free_status:'not yet surveyed',rule:'Route on mapped paths only; do not cross cultivated beds or mapped boundaries.',garden_profiles:accessProfiles},current_location:currentLocation,places:places.map(p=>({id:p.id,name:p.name,category:p.category,center:[p.ll.lng,p.ll.lat],access:accessProfiles[p.id]||null,source_url:'https://www.openstreetmap.org/'+p.id})),barriers:[...features.filter(f=>f.properties?.barrier&&isLine(f)&&!supersededBarriers.has(f.id)).map(f=>({id:f.id,kind:f.properties.barrier,fence_type:f.properties.fence_type||null,coordinates:f.geometry.coordinates,source:'openstreetmap'})),...GD.features.filter(f=>['fence','wall','hedge'].includes(f.properties.kind)&&f.geometry.type==='LineString').map(f=>({id:f.id,kind:f.properties.kind==='wall'?'wall':f.properties.kind,fence_type:f.properties.fence_type||f.properties.material||null,coordinates:f.geometry.coordinates,garden:f.properties.garden,source:'aerial-2026'}))],garden_detail:{source:'Google Maps 3D aerial imagery, manual trace, September 2026',walks:GD.features.filter(f=>f.properties.kind==='walk').length,routing_segments:GD.routing_segments.length,superseded_source_ways:GD.superseded_ways,gates:GD.features.filter(f=>f.properties.kind==='gate').map(f=>({name:f.properties.name,garden:f.properties.garden,coordinates:f.geometry.coordinates}))},path_segments:features.filter(f=>f.properties?.highway&&pathTypes.has(f.properties.highway)&&isLine(f)&&!['no','private'].includes(f.properties.access)&&!['no','private'].includes(f.properties.foot)).length,manual_route:exportRoute()};}
$('about').onclick=()=>$('notes').showModal();$('closeNotes').onclick=()=>$('notes').close();$('notes').onclick=e=>{if(e.target===$('notes')){const r=$('notes').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('notes').close();}};
const inside=f=>{const ll=L.latLng(center(f));return ll.lat>=38.7039&&ll.lat<=38.7164&&ll.lng>=-77.0978&&ll.lng<=-77.0781;};const local=features.filter(inside);$('stats').innerHTML=[['Buildings',local.filter(f=>f.properties.building).length],['Path segments',local.filter(f=>f.properties.highway&&pathTypes.has(f.properties.highway)).length],['Information boards',local.filter(f=>f.properties.information==='board').length]].map(([n,v])=>'<span><b>'+v+'</b>'+n+'<br>in estate bounding box</span>').join('');
window.mountVernonMap={map,source:window.ESTATE,exportRoute,getNavigationContext,setAccessProfile,applyAiRoute,locate:()=>$('locate').click(),addStop:osmId=>{const f=byId.get(osmId);if(!f||stops.some(s=>s.id===osmId))return false;stops.push({...placeById.get(osmId),id:osmId,name:placeById.get(osmId)?.name||f.properties.name||osmId,feature:f,ll:L.latLng(center(f))});renderRoute();return true;},clearRoute:()=>{stops=[];renderRoute();},clearAiRoute:()=>aiRouteLayer.clearLayers()};
renderPlaces();renderRoute();$('core').click();updateLabels();
